name: release

on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write

jobs:
    release:
        name: Create a draft release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create release draft
              env:
                  GH_TOKEN: ${{ github.token }}
              run: gh release create ${{ github.ref_name }} --generate-notes --draft
